=== AIDOaRt-VCE-Team/Solution-framework/VEL/VEL.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- ========== TOP LEVEL ELEMENTS  ==========-->
	<xs:element name="variability-exchange-models" type="VariabilityExchangeModels"/>
	<!-- ========== VARIABILITY EXCHANGE MODEL(S) ========== -->
	<xs:complexType name="VariabilityExchangeModels">
		<xs:complexContent>
			<xs:extension base="Identifiable">
				<xs:sequence>
					<xs:element name="version" type="xs:unsignedInt"/>
					<xs:element name="variability-exchange-model" type="VariabilityExchangeModel" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="VariabilityExchangeModel">
		<xs:complexContent>
			<xs:extension base="Identifiable">
				<xs:sequence>
					<xs:group ref="variationpoint-group" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="type" type="VariabilityExchangeModelTypeEnum" use="required"/>
				<xs:attribute name="uri" type="xs:anyURI" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- ========== VARIATIONPOINT ========== -->
	<xs:complexType name="VariationPoint" abstract="true">
		<xs:complexContent>
			<xs:extension base="Identifiable">
				<xs:sequence>
					<xs:element name="bindingtime" type="BindingTime" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="variable-artifact" type="ArtifactElement" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="type" type="VariationPointTypeEnum" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:group name="variationpoint-group">
		<xs:choice>
			<xs:element name="structural-variationpoint" type="StructuralVariationPoint"/>
			<xs:element name="parameter-variationpoint" type="ParameterVariationPoint"/>
		</xs:choice>
	</xs:group>
	<xs:complexType name="BindingTime">
		<xs:sequence>
			<xs:element name="name" type="BindingTimeEnum"/>
			<xs:element name="condition" type="Expression" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="selected" type="xs:boolean" use="optional"/>
	</xs:complexType>
	<!--Individual variation points-->
	<xs:complexType name="StructuralVariationPoint">
		<xs:complexContent>
			<xs:extension base="VariationPoint">
				<xs:sequence>
					<xs:element name="variation" type="StructuralVariation" minOccurs="1" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ParameterVariationPoint">
		<xs:complexContent>
			<xs:extension base="VariationPoint">
				<xs:sequence>
					<xs:element name="variation" type="ParameterVariation" minOccurs="1" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- ========== VARIATION ========== -->
	<xs:complexType name="Variation" abstract="true">
		<xs:complexContent>
			<xs:extension base="Identifiable">
				<xs:sequence>
					<xs:element name="hierarchy" type="VariationPointHierarchy" minOccurs="0" maxOccurs="1"/>
					<xs:element name="dependency" type="VariationDependency" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="condition" type="Expression" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
				<xs:attribute name="selected" type="xs:boolean" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="VariationPointHierarchy">
		<xs:complexContent>
			<xs:extension base="Identifiable">
				<xs:sequence>
					<xs:element name="variationpoint" minOccurs="1" maxOccurs="unbounded">
						<xs:complexType>
							<xs:attribute name="ref" type="xs:IDREF" use="required"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="VariationDependency">
		<xs:complexContent>
			<xs:extension base="Identifiable">
				<xs:sequence>
					<xs:element name="variation" minOccurs="1" maxOccurs="unbounded">
						<xs:complexType>
							<xs:attribute name="ref" type="xs:IDREF" use="required"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="condition" type="Expression" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
				<xs:attribute name="type" type="VariationDependencyEnum" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!--Individual variations-->
	<xs:complexType name="StructuralVariation">
		<xs:complexContent>
			<xs:extension base="Variation">
				<xs:sequence>
					<xs:element name="variable-artifact" type="ArtifactElement" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ParameterVariation">
		<xs:complexContent>
			<xs:extension base="Variation">
				<xs:sequence>
					<xs:element name="expression" type="Expression" minOccurs="0" maxOccurs="1"/>
					<xs:element name="value" type="xs:string" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- ========== EXPRESSIONS ========== -->
	<xs:complexType name="Expression">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" type="ExpressionLanguageEnum" use="required"/>
				<xs:attribute name="datatype" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<!--=========== Special Data ============-->
	<xs:complexType name="SpecialData">
		<xs:sequence>
			<xs:element name="data" type="KeyValuePair" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="KeyValuePair">
		<xs:sequence>
			<xs:element name="key">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="value">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="type" type="xs:string" use="optional"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<!-- ========== ENUMERATIONS ========== -->
	<xs:simpleType name="VariabilityExchangeModelTypeEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="variationpoint-description"/>
			<xs:enumeration value="variationpoint-configuration"/>
			<xs:enumeration value="variationpoint-partial-configuration"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="VariationPointTypeEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="optional"/>
			<xs:enumeration value="or"/>
			<xs:enumeration value="xor"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- ========== EXTENDABLE ENUMERATIONS ========== -->
	<xs:simpleType name="EnumerationExtension">
		<xs:restriction base="xs:string">
			<xs:pattern value="x:\S+"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="BindingTimeBaseEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="requirements-time"/>
			<xs:enumeration value="blueprint-derivation-time"/>
			<xs:enumeration value="model-construction-time"/>
			<xs:enumeration value="model-simulation-time"/>
			<xs:enumeration value="code-generation-time"/>
			<xs:enumeration value="preprocessor-time"/>
			<xs:enumeration value="compile-time"/>
			<xs:enumeration value="link-time"/>
			<xs:enumeration value="flash-time"/>
			<xs:enumeration value="post-build"/>
			<xs:enumeration value="post-build-loadable-time"/>
			<xs:enumeration value="post-build-selectable-time"/>
			<xs:enumeration value="run-time"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="BindingTimeEnum">
		<xs:union memberTypes="BindingTimeBaseEnum EnumerationExtension"/>
	</xs:simpleType>
	
	<xs:simpleType name="VariationDependencyBaseEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="requires"/>
			<xs:enumeration value="conflicts"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="VariationDependencyEnum">
		<xs:union memberTypes="VariationDependencyBaseEnum EnumerationExtension"/>
	</xs:simpleType>
	
	<xs:simpleType name="ExpressionLanguageBaseEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="single-feature-condition"/>
			<xs:enumeration value="and-feature-condition"/>
			<xs:enumeration value="or-feature-condition"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ExpressionLanguageEnum">
		<xs:union memberTypes="ExpressionLanguageBaseEnum EnumerationExtension"/>
	</xs:simpleType>
		
	<!-- ========== AUXILIARY DATA TYPES ========== -->
	<xs:complexType name="Identifiable" abstract="true">
		<xs:sequence>
			<xs:element name="special-data" type="SpecialData" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="ArtifactElement">
		<xs:sequence>
			<xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="type" type="xs:string" use="optional"/>
		<xs:attribute name="uri" type="xs:anyURI" use="optional"/>
	</xs:complexType>
</xs:schema>

=== AIDOaRt-VCE-Team/Solution-framework/VEL/examples/specification-variationpoint-dependency-type.xml
<?xml version="1.0" encoding="UTF-8"?>
<variability-exchange-models id="root" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../VEL.xsd">
	<version>1</version>
	<variability-exchange-model type="variationpoint-description" id="model">
		<structural-variationpoint id="vp1" type="optional">
			<variation id="vp1v1">
				<condition type="single-feature-condition">Feature1</condition>
			</variation>
		</structural-variationpoint>
		<structural-variationpoint id="vp2" type="optional">
			<variation id="vp2v1">
				<dependency type="conflicts" id="vp2d1">
					<variation ref="vp1v1"/>
				</dependency>
				<condition type="single-feature-condition">Feature1</condition>
			</variation>
			<variation id="vp2v2">
				<condition type="single-feature-condition">Feature2</condition>
			</variation>
			<variation id="vp2v3">
				<condition type="single-feature-condition">Feature3</condition>
			</variation>
		</structural-variationpoint>
	</variability-exchange-model>
</variability-exchange-models>

=== AIDOaRt-VCE-Team/Solution-framework/VEL/examples/SPES-FAS-description-model-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<variability-exchange-models id="root" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../VEL.xsd">
	<version>1</version>
	<variability-exchange-model type="variationpoint-description" id="spes">
		<parameter-variationpoint id="vp1" name="VAR_DEMO_FAS_Distronic" type="xor">
			<variation id="vp1v1" name="disabled">
				<value>0</value>
			</variation>
			<variation id="vp1v2" name="enabled">
				<value>1</value>
			</variation>
		</parameter-variationpoint>
		<!-- There is no vp2 because Limiter is not a variation point in the configuration model of stage 4 -->
		<parameter-variationpoint id="vp3" name="VAR_DEMO_FAS_EmergencyBrake" type="xor">
			<variation id="vp3v1" name="disabled">
				<value>0</value>
			</variation>
			<variation id="vp3v2" name="enabled">
				<value>1</value>
			</variation>
		</parameter-variationpoint>
		<parameter-variationpoint id="vp4" name="VAR_DEMO_FAS_Repeater" type="xor">
			<variation id="vp4v1" name="disabled">
				<value>0</value>
			</variation>
			<variation id="vp4v2" name="enabled">
				<value>1</value>
			</variation>
		</parameter-variationpoint>
		<parameter-variationpoint id="vp5" type="xor">
			<variation id="vp5v1" name="disabled">
				<value>0</value>
			</variation>
			<variation id="vp5v2" name="enabled">
				<value>1</value>
			</variation>
		</parameter-variationpoint>
		<parameter-variationpoint id="vp6" name="VAR_DEMO_FAS_FollowToStop" type="xor">
			<variation id="vp6v1" name="disabled">
				<value>0</value>
			</variation>
			<variation id="vp6v2" name="enabled">
				<value>1</value>
			</variation>
		</parameter-variationpoint>
		<parameter-variationpoint id="vp7" name="VAR_DEMO_FAS_Tempomat" type="xor">
			<variation id="vp7v1" name="disabled">
				<value>0</value>
			</variation>
			<variation id="vp7v2" name="enabled">
				<value>1</value>
			</variation>
		</parameter-variationpoint>
	</variability-exchange-model>
</variability-exchange-models>

=== AIDOaRt-VCE-Team/Solution-framework/VEL/examples/specification-binding-times-description.xml
<?xml version="1.0" encoding="UTF-8"?>
<variability-exchange-models id="root" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../VEL.xsd">
	<version>1</version>
	<variability-exchange-model type="variationpoint-description" id="model">
		<structural-variationpoint id="vp1" type="optional">
			<bindingtime>
				<name>preprocessor-time</name>
			</bindingtime>
			<variation id="vp1v1">
				<condition type="single-feature-condition">Feature1</condition>
			</variation>
		</structural-variationpoint>
		<structural-variationpoint id="vp2" type="optional">
			<bindingtime>
				<name>preprocessor-time</name>
				<condition type="single-feature-condition">SmallSoftwareFootprint</condition>
			</bindingtime>
			<bindingtime>
				<name>post-build</name>
				<condition type="single-feature-condition">LargeSoftwareFootprint</condition>
			</bindingtime>
			<variation id="vp2v1">
				<condition type="single-feature-condition">Feature1</condition>
			</variation>
		</structural-variationpoint>
	</variability-exchange-model>
</variability-exchange-models>

=== AIDOaRt-VCE-Team/Solution-framework/VEL/examples/specification-expression-type.xml
<?xml version="1.0" encoding="UTF-8"?>
<variability-exchange-models id="root" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../VEL.xsd">
	<version>1</version>
	<variability-exchange-model type="variationpoint-configuration" id="model">
		<structural-variationpoint id="vp1" type="xor">
			<variation id="vp1v1">
				<condition type="single-feature-condition" datatype="bool">Feature1</condition>
			</variation>
			<variation id="vp1v2">
				<condition type="and-feature-condition" datatype="bool">Feature2,Feature3</condition>
			</variation>
			<variation id="vp1v3">
				<condition type="or-feature-condition" datatype="bool">
					Feature4, Feature5, Feature6
				</condition>
			</variation>
			<variation id="vp1v4">
				<condition type="x:pvscl" datatype="ps:boolean">
					Feaure7 AND Feature8
				</condition>
			</variation>
		</structural-variationpoint>
	</variability-exchange-model>
</variability-exchange-models>

=== AIDOaRt-VCE-Team/Solution-framework/VEL/examples/specification-xor-structural-variationpoint.xml
<?xml version="1.0" encoding="UTF-8"?>
<variability-exchange-models id="root" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../VEL.xsd">
	<version>1</version>
	<variability-exchange-model type="variationpoint-description" id="model">
		<structural-variationpoint id="vp1" type="xor">
			<variation id="vp1v1" name="Alternative 1">
				<condition type="single-feature-condition">Feature1</condition>
			</variation>
			<variation id="vp1v2" name="Alternative 2">
				<condition type="single-feature-condition">Feature2</condition>
			</variation>
			<variation id="vp1v3" name="Alternative 3">
				<condition type="single-feature-condition">Feature3</condition>
			</variation>
		</structural-variationpoint>
	</variability-exchange-model>
</variability-exchange-models>

=== AIDOaRt-VCE-Team/Solution-framework/VEL/examples/example_multiple_binding_times.xml
<?xml version="1.0" encoding="UTF-8"?>
<variability-exchange-models id="root" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../VEL.xsd">
	<version>1</version>
	<variability-exchange-model type="variationpoint-description" id="m1">
		<!-- A variationpoint with multiple binding times. This means that the bindingtime for this variationpoint has not yet been decided.-->
		<structural-variationpoint id="vp1" type="optional">
			<bindingtime>
				<name>code-generation-time</name>
			</bindingtime>
			<bindingtime>
				<name>preprocessor-time</name>
			</bindingtime>
			<bindingtime>
				<name>compile-time</name>
			</bindingtime>
			<variation id="vp1v1">
				<condition type="single-feature-condition">Feature1</condition>
			</variation>
		</structural-variationpoint>
		<structural-variationpoint id="vp2" type="optional">
			<!-- A variationpoint with multiple binding times. One binding time is selected (that is, a binding time has been decided for the variationpoint); the other(s) can be ignored. -->
			<bindingtime selected="true">
				<name>code-generation-time</name>
			</bindingtime>
			<bindingtime>
				<name>post-build</name>
			</bindingtime>
			<variation id="vp2v1">
				<condition type="single-feature-condition">Feature1</condition>
			</variation>
		</structural-variationpoint>
		<structural-variationpoint id="vp3"  type="optional">
			<!-- Same as above, but the attribute selected is present on all binding times. -->
			<bindingtime selected="true">
				<name>code-generation-time</name>
			</bindingtime>
			<bindingtime selected="false">
				<name>post-build</name>
			</bindingtime>
			<variation id="vp3v1">
				<condition type="single-feature-condition">Feature1</condition>
			</variation>
		</structural-variationpoint>
	</variability-exchange-model>
</variability-exchange-models>

=== AIDOaRt-VCE-Team/Solution-framework/AutomationML_Modeling/VEL/examples/specification-special-data-type.xml
<?xml version="1.0" encoding="UTF-8"?>
<variability-exchange-models id="root" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../VEL.xsd">
	<special-data name="CreatorInfo">
		<data>
			<key>Creator</key>
			<value>SPES </value>
		</data>
		<data>
			<key>Created</key>
			<value type="xs:date">1998-11-17</value>
		</data>
	</special-data>
	<version>1</version>
	<variability-exchange-model type="variationpoint-configuration" id="model">
		<structural-variationpoint id="vp1" name="optional variationpoint" type="optional">
			<special-data name="CreatorInfo">
				<data>
					<key>Created</key>
					<value type="xs:date">1998-11-17</value>
				</data>
			</special-data>
			<variation id="vp1v1" name="optional variation">
				<condition type="single-feature-condition">Feature1</condition>
			</variation>
		</structural-variationpoint>
	</variability-exchange-model>
</variability-exchange-models>

=== AIDOaRt-VCE-Team/Solution-framework/VEL/examples/specification-artifact-element-type.xml
<?xml version="1.0" encoding="UTF-8"?>
<variability-exchange-models id="root" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../VEL.xsd">
	<version>1</version>
	<variability-exchange-model type="variationpoint-configuration" id="model">
		<structural-variationpoint id="vp1" type="optional">
			<variation id="vp1v1">
				<condition type="single-feature-condition">Feature1</condition>
				<variable-artifact uri="file:///C:/SPES/file1.c"/>
			</variation>
		</structural-variationpoint>
		<structural-variationpoint id="vp2" type="optional">
			<variation id="vp2v1">
				<condition type="single-feature-condition">Feature1</condition>
				<variable-artifact type="simulink">
					<simulink-id>12</simulink-id>
				</variable-artifact>
			</variation>
		</structural-variationpoint>
	</variability-exchange-model>
</variability-exchange-models>
